### ISSUE TITLE
I try to compile in kali

### ISSUE THREAD

**Issue by dodoaska** [geemion/Khepri#11]
my mistake , 
i delete and add again 
git clone --recursive https://github.com/geemion/Khepri

next :
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
protoc -I=/root/Khepri/proto --go_out=/root/Khepri/src /root/Khepri/proto\client.proto
or
protoc -I=[/root/Khepri/proto] --go_out=[/root/Khepri/src] [/root/Khepri/proto]\client.proto

#  protoc -I=/root/Khepri/proto --go_out=/root/Khepri/src /root/Khepri/proto\client.proto                                                                     
Could not make proto path relative: /root/Khepri/protoclient.proto: No such file or directory

protoc -I=[proto] --go_out=[src] [proto]\client.proto                                                                                                       1 ⨯
[proto]: warning: directory does not exist.
Could not make proto path relative: [proto]client.proto: No such file or directory


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

./gen-mk-project.sh   
mkdir buildmk
CMake Error: The source directory "/root/Khepri" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
./gen-mk-project.sh: line 12: -DVCPKG_TARGET_TRIPLET=x64-linux: command not found
make: *** No targets specified and no makefile found.  Stop.

I edit the gen-mk-project.sh    
-DCMAKE_TOOLCHAIN_FILE="/root/vcpkg/scripts/buildsystems/vcpkg.cmake"\       #edit it

how i have same error 
mkdir buildmk
CMake Error: The source directory "/root/Khepri" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
./gen-mk-project.sh: line 12: -DVCPKG_TARGET_TRIPLET=x64-linux: command not found
make: *** No targets specified and no makefile found.  Stop.

I dont want make mistake

**Comment by dodoaska** [comment]
I want use for surface and prioritize my small network

**Comment by geemion** [comment]
_CMake Error: The source directory "/root/Khepri" does not appear to contain CMakeLists.txt._  
This error is obvious, Your current dir is "/root/Khepri", but the CMakeLists.txt is in "/root/Khepri/src/beacon" .
Maybe you can change you bash current dir to fix it

**Comment by dodoaska** [comment]
I will do

**Comment by dodoaska** [comment]
for me is hard to install , i will use another programs for test my networks
