### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by whoami-Root** [geemion/Khepri#14]
F:\Khepri\src\teamserver>go build cmd\teamserver\teamserver.go
cmd\teamserver\teamserver.go:21:2: use of internal package teamserver/internal/conf not allowed
cmd\teamserver\teamserver.go:22:2: use of internal package teamserver/internal/rpc not allowed

以及teamclient
CMake Error at C:/Program Files (x86)/vcpkg/scripts/buildsystems/vcpkg.cmake:861 (_find_package):
  Found package configuration file:

    C:/Program Files/grpc/lib/cmake/grpc/gRPCConfig.cmake

  but it set gRPC_FOUND to FALSE so package "gRPC" is considered to be NOT
  FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing: absl::base
  absl::core_headers absl::memory absl::status absl::cord absl::str_format
  absl::strings absl::synchronization absl::time absl::optional
  absl::flat_hash_map absl::inlined_vector absl::bind_front absl::hash
  absl::statusor absl::variant absl::utility protobuf::libprotobuf
  protobuf::libprotoc

Call Stack (most recent call first):
  CMakeLists.txt:98 (find_package)

-- Configuring incomplete, errors occurred!
See also "F:/Khepri/src/teamclient/buildvc64/CMakeFiles/CMakeOutput.log".

**Comment by geemion** [comment]
Please refer https://github.com/golang/go/issues/26446 and https://github.com/geemion/Khepri/blob/main/docs/quick_start.md
