### ISSUE TITLE
teamclient编译问题 求助

### ISSUE THREAD

**Issue by NO3389** [geemion/Khepri#17]
beacon已经编译成功
cmake报错
![image](https://user-images.githubusercontent.com/106858226/171985621-a4fda35a-722b-49a3-a1ac-aa3deb4eb4d5.png)

VS2015中
![image](https://user-images.githubusercontent.com/106858226/171985660-9881a749-0105-4176-a94c-27012325ead0.png)
![image](https://user-images.githubusercontent.com/106858226/171985670-65fb48fe-d6d7-4e73-8f77-3e3b376065c3.png)

前提是 在protoc -I=[Khepri Proto Dir] --go_out=plugins=grpc:[Khepri Src Dir] -I=[Khepri Proto Dir]\teamrpc.proto 时显示 Missing input file. 
![image](https://user-images.githubusercontent.com/106858226/171985793-1193cb5d-0f90-4476-8794-d5f6e2e95ebf.png)
后面我把 -I=去掉 为 protoc -I=C:\src\Khepri\proto --go_out=plugins=grpc:C:/src/Khepri/src C:/src/Khepri/proto/teamrpc.proto 不知道有没有影响

**Comment by geemion** [comment]
Please refer the document https://github.com/geemion/Khepri/blob/main/docs/quick_start.md#clone-and-generate-the-protobuffer-code

```
protoc -I=[Khepri Proto Dir] --grpc_out="[Khepri Proto Dir]\..\src\proto_autogen_cpp" --plugin=protoc-gen-grpc="[Khepri Proto Dir]\grpc_cpp_plugin.exe" [Khepri Proto Dir]\teamrpc.proto
```
