### ISSUE TITLE
beacan编译求助

### ISSUE THREAD

**Issue by xiaoheiwo** [geemion/Khepri#2]
你好 非常感想您解决我上一个teamserver问题,我成功编译了他,   现在我又碰到新问题了.
我使用的环境如下
```
window10
vs2019 
cmake最新
vcpkg 
ming-w64 
```
我尝试编译beacon 
我使用vcpkg安装了cryptopp、protobuf
```
vcpkg install cryptopp:x64-windows-static
vcpkg install protobuf:x64-windows-static
```
我在vcpkg上面并没有找到yasio的包  于是我去gitlab参照官方教程

一开始我是把yasio编译成lib文件 但是我发现这样并不行
我尝试把yasio的源码放在beacon项目的yasio目录里
使用如下命令 生成了vs的工程文件 
```cmake -S . -B buildvc64    -DCMAKE_TOOLCHAIN_FILE="C:/dev/vcpkg-master/scripts/buildsystems/vcpkg.cmake"     -DVCPKG_TARGET_TRIPLET="x64-windows-static"```

我使用vs2019打开工程后 一直提示我 yasio/yasio.hpp等相关文件无法找到  
```
于是我把include"yasio/yasio.hpp" 
改成了include"yasio.hpp"
```
解决了这个问题 但是新的问题又出现了 
![image](https://user-images.githubusercontent.com/37685546/131794615-9bed4fb5-5d40-4c39-b5fc-5543b83fd059.png)
以及下面很多很多 错误 

希望师傅可以将你使用的环境告知一下  非常感谢   

从来没有使用cmake编译项目 好难

**Comment by geemion** [comment]
- 1.yasio依赖，可以直接 git clone --recursive https://github.com/geemion/Khepri 克隆yasio，我之前文档写的有点问题，抱歉。。。
- 2.你这个报错原因是protobuf版本不一致的原因，主要是protoc.exe工具和vcpkg安装的protobuf版本不一致， 你直接拷贝vcpkg目录安装的protoc工具，路径和这个[vcpkg root]\installed\x64-windows-static\tools\protobuf\protoc.exe 差不多。

我都更新到quick_start中了，如果你编译过程中还有其他问题的话也可以写上来，如果没有问题了 就可以把这个问题关了。

**Comment by xiaoheiwo** [comment]
非常感谢 我刚刚也发现是版本问题     可能还会又新的问题  我先关闭次问题
