### ISSUE TITLE
How to install khepri of mac os ?????

### ISSUE THREAD

**Issue by pullghjunkkk** [geemion/Khepri#20]
chikkachun@chikdeMBP ~ % git clone https://github.com/geemion/Khepri 
fatal: destination path 'Khepri' already exists and is not an empty directory.
chikkachun@chikdeMBP ~ % git clone https://github.com/geemion/Khepri.git
fatal: destination path 'Khepri' already exists and is not an empty directory.
chikkachun@chikdeMBP ~ % cd kheproi
cd: no such file or directory: kheproi
chikkachun@chikdeMBP ~ % git clone --recursive https://github.com/geemion/Khepri 
fatal: destination path 'Khepri' already exists and is not an empty directory.
chikkachun@chikdeMBP ~ %

**Comment by geemion** [comment]
please refer: https://github.com/geemion/Khepri/blob/main/docs/quick_start.md
