### ISSUE TITLE
Error in compiling teamserver

### ISSUE THREAD

**Issue by PZRdUqv15P** [geemion/Khepri#4]
Hi, I've been compiling this project for a whole week now, after generating the protobuf and grpc codes for teamserver I encountered following error.
```
# teamserver/internal/proto/protobuf
internal/proto/protobuf/teamrpc_grpc.pb.go:21:33: undefined: LoginUserReq
internal/proto/protobuf/teamrpc_grpc.pb.go:21:74: undefined: LoginUserRsp
internal/proto/protobuf/teamrpc_grpc.pb.go:23:37: undefined: ServerCmdReq
internal/proto/protobuf/teamrpc_grpc.pb.go:23:78: undefined: ServerCmdRsp
internal/proto/protobuf/teamrpc_grpc.pb.go:34:63: undefined: LoginUserReq
internal/proto/protobuf/teamrpc_grpc.pb.go:34:104: undefined: LoginUserRsp
internal/proto/protobuf/teamrpc_grpc.pb.go:53:8: undefined: CommandReq
internal/proto/protobuf/teamrpc_grpc.pb.go:54:11: undefined: CommandRsp
internal/proto/protobuf/teamrpc_grpc.pb.go:62:54: undefined: CommandReq
internal/proto/protobuf/teamrpc_grpc.pb.go:66:55: undefined: CommandRsp
internal/proto/protobuf/teamrpc_grpc.pb.go:66:55: too many errors
```
What's the problem here?

FYI I noticed a typo in protobuf code generating section in the doc
`protoc -I=[Khepri Proto Dir] --go_out=plugins=grpc:[Khepri Src Dir] -I=[Khepri Proto Dir]\teamrpc.proto`
Will produce error `Missing input file.` Instead I think this should be
`protoc -I=[Khepri Proto Dir] --go_out=plugins=grpc:[Khepri Src Dir] [Khepri Proto Dir]\teamrpc.proto`
Don't know if this is correct.

Regards.

**Comment by geemion** [comment]
### This project was created for educational purposes and should not be used in environments without legal authorization.
