### ISSUE TITLE
只能监听本地地址 无法上线

### ISSUE THREAD

**Issue by xiaoheiwo** [geemion/Khepri#6]
listening 只能监听0.0.0.0 无法监听其他地址 
不能监听服务器地址就无法上线    只能监听0.0.0.0 生成的beacon 中的请求地址 也是0.0.0.0 这样就导致无法上线

当我尝试监听 其他地址时
![image](https://user-images.githubusercontent.com/37685546/131960025-d8f5449f-c6b3-4176-b742-b2422e1e602a.png)

![image](https://user-images.githubusercontent.com/37685546/131959876-9abbb7c6-238a-4142-96ce-837fce29cf5d.png)

**Comment by geemion** [comment]
https://www.google.com/search?q=bind+cannot+assign+requested+address
先自己尝试独立解决事实呢，不要刷issue  看你自己开了几个issue 然后又关了。。。。。。。

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md#%E5%9C%A8%E6%8F%90%E9%97%AE%E4%B9%8B%E5%89%8D

**Comment by geemion** [comment]
### **This project was created for educational purposes and should not be used in environments without legal authorization.**

**Comment by xiaoheiwo** [comment]
ok
