### ISSUE TITLE
您好，师傅，系统的学习了您的代码，感触很多，自己也有一些问题

### ISSUE THREAD

**Issue by ro0tmylove** [geemion/Khepri#7]
beacon代码
win端beacon 因为是c++控制台程序特性，如果代码不加getchar程序就直接退出，运行出现黑框是个很难受的问题，尝试更改子系统为windows隐藏黑框 但是这样的话getchar函数没有任何意义 运行任然自动退出
我尝试创建线程启动yasio start方法 可惜无奈自己是个菜鸡 执行后出现空指针报错 目前任没有头绪

我想着能和师傅一起开发此项目 （虽然我很菜） 并且我想着能结合红队渗透思路 已经横向的思想方法 对项目进行整体构建 希望您能给我这个机会
我深感荣幸 对我来说也是一种锻炼

**Comment by geemion** [comment]
谢谢你，我建议你可以先看下相关书，系统学习下C/C++，比如可以看下Windows核心编程、C++ Primer. 
你遇到的问题可以直接加一个死循环就可以了，
`while(1){
sleep(100);
}`
如果你想参与这个项目，你可以拉一个分支 然后开发，不过本项目主要是学习目的 学习C++、Golang编程，方向可能和你提到的可能不一致。

**Comment by ro0tmylove** [comment]
好的 非常感谢您提的建议 因为我主要是学的渗透测试 安全方面 开发做的相对较少 就想着能把实战中的一些成分融入到您的项目中去 再次衷心感谢

Young ***@***.***> 于2021年9月9日周四 下午7:36写道：
